default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: pagink_development


test:
  <<: *default
  database: pagink_test


production:
  <<: *default
  database: pagink_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  url: <%= ENV['DB_HOST'] %>
  database: heroku_c583923e39cbd7a